### ISSUE TITLE
远景论坛维护中了，看不到链接

### ISSUE THREAD

**Issue by ACY-CAT** [lgs3137/PAVILION_Gaming_NB-macOS#3]
可以的话，教程求大佬发邮箱（1394294469@qq.com）
装完mac后win没有了,怎么都恢复不了，clover引导还是显示安装mac，oc引导才能进mac

**Comment by lgs3137** [comment]
Update Clover5107 & Kext & OC0.5.7.（纯更新，未在真机测试！）
